# This workflow will install dependencies and create a build suitable
# to be used in an AWS Lambda Layer.  The build will then be uploaded
# to S3 and then can be accessed from any lambda that uses the layer.
#
# This build is only for dev builds.  Releases will be built from a
# seperate action.
#
# A new version of the layer will be created for every branch when a
# pull request is initiated.  This allows us to test the layer in a
# dev environment on AWS BEFORE the code is merged into master.


name: Build Release Lambda Layer

on:
  release:
    types: [created]

jobs:
  # For more info: https://github.com/aws-actions/configure-aws-credentials

  deploy:
    name: Upload package to 'build' account
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Build Layer, zip it all up and upload S3
        env:
          release_bucket_uri: 's3://net.dilex.build.deployments/release/Yacs'
        run: |
          mkdir python
          pip install -r requirements/prod.txt -t python
          pip install . -t  python
          echo building release $release_id
          zip --quiet -r layer.zip python
          aws s3 cp layer.zip $release_bucket_uri/Yacs-$(python setup.py --version).zip

